# -*- coding: utf-8 -*-
"""Apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lqWRmBFK6VhDL1gP4fHmg8_YVFF5s4pt

# Apriori Association Rule

## Importing the Libraries
"""

!pip install apyori

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the Dataset"""

dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None)

transactions = []
for i in range(0, 7501):
  transactions.append([str(dataset.values[i,j] for j in range(0,20))])

print(transactions)

"""## Training the Apriori Model on the dataset(transactions list) :

"""

from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length=2)

"""## Visualizing the results

### Displaying the output returned by the function as it is:
"""

results = list(rules)
results

"""### Put the results well organised into pandas dataframe"""

### Find a code from chat gpt and dont memorise the code

"""### Displaying the results non-sorted"""

### resultsInDataframe

"""### Displaying the results sorted"""

### resultsInDataframe.nLargest(n = 10, columns = 'lift')