# -*- coding: utf-8 -*-
"""Decision Tree Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wNxO-sbXiBYl2oUWkjH4V0leVI2n4gyF

# Decision Tree Regression

## Importing the Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the Dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

print(X)

print(y)

"""## Training the Decision Tree Regression Model on the whole dataset"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X, y)

"""## Predicting a Result"""

regressor.predict([[6.5]])

"""## Visualizing the Result (Normal View)"""

plt.scatter(X, y, color='red')
plt.plot(X, regressor.predict(X), color='blue')
plt.title('Position vs Salary (Normal View)')
plt.xlabel('Position')
plt.ylabel('Salary')
plt.show()

"""## Visualizing the Result (High Resolution View or Decision Tree View)"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid),1))
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor.predict(X_grid), color='blue')
plt.title('Position vs Salary (Normal View)')
plt.xlabel('Position')
plt.ylabel('Salary')
plt.show()