# -*- coding: utf-8 -*-
"""UCB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msInnwZl8LsT3ZoX7twVtci1RP3-nWcP

# Upper Confidence Bound (UCB)

## Importing the Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the Dataset"""

dataset = pd.read_csv('Ads_CTR_Optimisation.csv')

"""## Implementing UCB"""

import math
N = 10000
d = 10
ads_selected = []
numbers_of_selections = [0]*10
sums_of_rewards = [0]*10
total_reward = 0
for n in range(0,N):
  ad = 0
  max_upper_bound = 0
  for i in range(0,d):
    if numbers_of_selections[i] > 0 :
      average_reward = sums_of_rewards[i]/numbers_of_selections[i]
      delta_i = math.sqrt(3/2*math.log(n+1)/numbers_of_selections[i])
      upper_bound = average_reward + delta_i
    else :
      upper_bound = 1e400
    if upper_bound > max_upper_bound :
      max_upper_bound = upper_bound
      ad = i
  ads_selected.append(ad)
  numbers_of_selections[ad]+=1
  reward = dataset.values[n,ad]
  sums_of_rewards[ad]+=reward
  total_reward += reward

"""## Visualizing the Results"""

plt.hist(ads_selected)
plt.title('Histogram of ads selected')
plt.xlabel('Ads')
plt.ylabel('No. of times each ad was selected')
plt.show()